spring:
  application:
    name: projectA

  boot:
    admin:
      client:
        url:
          - http://localhost:1111/

server:
  port: 2222

#eureka:
    #client:
    #service-url:
  #defaultZone: http://localhost:8761/
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
